name: blogger
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  provider: ^6.0.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  cached_network_image: ^3.3.0
  connectivity_plus: ^4.0.2
  shimmer: ^3.0.0
  lottie: ^2.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/lottie/
    - assets/images/

